version: "3.8"
services:
    rails:
        build: ./REST_API
        command: "rails s"
        volumes:
            - ./REST_API:/app
        ports:
            - "3000:3000"
    ember:
        build: ./FrontEnd
        ports: 
            - "8080:80"
